// @vitest-environment node
/// <reference types="node" />
//
// tsconfig.test.json pins an explicit `types` list without "node", so the
// reference directive above pulls in @types/node for this file only.
//
// `canopy.gen.ts` is generated by scripts/gen_ts_types.py from the event
// JSON Schemas (GET /schemas). Two checks keep the checked-in file honest:
//
// 1. Always: the digest in the generated header equals the SHA-256 of the
//    checked-in schemas fixture (`canopy.schemas.json`), and the file exports
//    one type per kind in that fixture. This needs no Python, so the frontend
//    CI job can run it. The Python side (tests/test_api_gateway.py) asserts
//    the fixture equals a fresh `event_schemas()` and the .ts equals a fresh
//    render, which closes the loop.
// 2. When `uv` is on PATH (the root environment, `make check`): regenerate
//    through the real script with `--check` and require it to report up to
//    date. Skipped, not failed, where uv is absent.
import { spawnSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { EVENT_KINDS } from './canopy.gen'

const GEN_TS = fileURLToPath(new URL('./canopy.gen.ts', import.meta.url))
const SCHEMAS_JSON = fileURLToPath(
  new URL('./canopy.schemas.json', import.meta.url),
)
const REPO = fileURLToPath(new URL('../..', import.meta.url))
const DIGEST_PREFIX = '// Schema digest: sha256:'

const generated = readFileSync(GEN_TS, 'utf8')
const fixtureBytes = readFileSync(SCHEMAS_JSON)
const fixture = JSON.parse(fixtureBytes.toString('utf8')) as Record<
  string,
  { title?: string }
>

const uvAvailable = (): boolean => {
  const probe = spawnSync('uv', ['--version'], { encoding: 'utf8' })
  return probe.status === 0
}

describe('types/canopy.gen parity with the event schemas', () => {
  it('carries the digest of the checked-in schemas fixture', () => {
    const line = generated
      .split('\n')
      .find((candidate) => candidate.startsWith(DIGEST_PREFIX))
    expect(line, 'generated header has no schema digest line').toBeDefined()
    const declared = line!.slice(DIGEST_PREFIX.length).trim()
    const actual = createHash('sha256').update(fixtureBytes).digest('hex')
    expect(declared).toBe(actual)
  })

  it('exports one type per event kind in the fixture, and the kind list', () => {
    const kinds = Object.keys(fixture)
    expect(kinds.length).toBeGreaterThan(0)
    expect([...EVENT_KINDS]).toEqual(kinds)
    for (const kind of kinds) {
      const name = fixture[kind].title
      expect(name, `schema for ${kind} has no title`).toBeTruthy()
      expect(generated).toMatch(new RegExp(`^export type ${name} = `, 'm'))
    }
    expect(kinds).toEqual(
      expect.arrayContaining([
        'signal',
        'anomaly',
        'attribution',
        'attribution_challenge',
        'decision',
        'ui_event',
        'trace',
        'embedding',
      ]),
    )
  })

  it('declares the withheld recovery block on Decision (spec §6, wave 4B)', () => {
    expect(generated).toMatch(/^export type WithheldRecovery = \{/m)
    expect(generated).toMatch(/withheld_recovery: WithheldRecovery \| null/)
  })

  it.skipIf(!uvAvailable())(
    'matches a fresh generation when uv is available',
    () => {
      const result = spawnSync(
        'uv',
        ['run', '--no-sync', 'python', 'scripts/gen_ts_types.py', '--check'],
        { cwd: REPO, encoding: 'utf8', timeout: 120_000 },
      )
      expect(
        result.status,
        `gen_ts_types.py --check failed:\n${result.stdout}\n${result.stderr}`,
      ).toBe(0)
    },
  )
})
